### PR TITLE
build(ci): remove 'publish.yml'

### PR DESCRIPTION
**Pull request by david-allison**
replaced on the server with:

```
docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --schedule "0 0 4 * * *"
```

### CODE REVIEW

**Comment by lauterb** [comment]
> replaced on the server with:
> 
> ```
> docker run -d --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --cleanup --schedule "0 0 4 * * *"
> ```
is it containrrr with three 'r's on purpose, like that recent movie RRR?

**Comment by david-allison** [comment]
It's intentional: 

* https://containrrr.dev/
* https://github.com/containrrr

**Comment by lauterb** [comment]
Awesome!

**Comment by david-allison** [comment]
Note that `-v /var/run/docker.sock:/var/run/docker.sock` is dangerous:

https://dejandayoff.com/the-danger-of-exposing-docker.sock/

**Comment by lauterb** [comment]
For a split second I thought the sock meant "sock puppet."

**Pull request merged**
