### PR TITLE
Add seek functionality for YouTube

### PR DESCRIPTION
**Pull request by lauterb**
* fixes:  #191

### CODE REVIEW

**Review by david-allison — COMMENTED** [review]
It would probably be useful to log the time that 'seek & play' was pressed

Probably better to mass-ignore a subset of errors here, as there's a lot of them and it makes the code harder to reason about

example:

```typescript
/* eslint-disable @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-assignment */

 /* eslint-enable */
```

Implementer's choice. Working functionality is better than nice to haves

**Comment by lauterb** [comment]
Please ignore last commit. :)

**Comment by lauterb** [comment]
^Feedback incorporated and rebased to a single commit

**Review by david-allison — APPROVED** [review]
Tried this tonight. Works great!

**Pull request merged**
